In [1]:
#导入需要的python模块
import scipy.io as sio
import numpy as np
import os
import re

In [7]:
# 加载数据集及其类别标签
path = '../dataset/train/'

data = np.array([])

label = []

for file in os.listdir(path):
    key = re.sub('.mat',"",file)
    y = re.sub("\D","",file)
    a = sio.loadmat(path+file)[key]
    class_num = a.shape[0]
    for _ in range(class_num):
        label.append(y)
    data = np.append(data,a)
    
data = data.reshape((-1,200))    
label = np.array(label,dtype=np.int32)

In [8]:
data

array([[3711., 4242., 4408., ..., 1064., 1019., 1023.],
       [3711., 4245., 4417., ..., 1042., 1023., 1019.],
       [3711., 4362., 4594., ..., 1044., 1024., 1009.],
       ...,
       [3186., 4114., 4213., ..., 1045., 1015., 1009.],
       [2586., 4114., 4226., ..., 1023., 1018., 1014.],
       [3189., 4118., 4492., ..., 1034., 1014., 1009.]])

In [9]:
label

array([11, 11, 11, ...,  2,  2,  2], dtype=int32)

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
# 划分训练集和验证集
X_train,X_valid,y_train,y_valid = train_test_split(
        data,label,test_size=0.3,shuffle=True)

scaler = StandardScaler() #将数据约束到同一尺度下
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_valid = scaler.transform(X_valid)

In [11]:
svc = SVC(C=10,gamma=0.01,class_weight='balanced')  #构建分类器，设定参数
svc.fit(X_train,y_train)
y_pred = svc.predict(X_valid)
print(accuracy_score(y_valid,y_pred))

0.9475457170356112


In [13]:
# 加载测试集
test_data = sio.loadmat("../dataset/data_test_final.mat")['data_test_final']
test_data = np.array(test_data, dtype=np.float64)

In [14]:
test_data.shape

(2310, 200)

In [15]:
x_test = scaler.transform(test_data)

In [16]:
y_test = svc.predict(x_test)
y_test

array([12,  5,  3, ..., 14, 12,  6], dtype=int32)

In [18]:
import pandas as pd
data = pd.DataFrame(y_test)
data.to_csv("../dataset/test_labels.csv")